### ISSUE TITLE
http_parse_headers function is not standard function 

### ISSUE THREAD

**Issue by kmpsharma** [montania/Google-Calendar-API-PHP-Class#2]
Hi,

In the script function http_parse_headers used 2-3 times but it is not standard php function. Please let me know if I am missing someting.

**Comment by mcls** [comment]
Hi,

If http_parse_headers doesn't work, you can use this function instead:

``` php
<?php
    function http_parse_headers( $header )
    {
        $retVal = array();
        $fields = explode("\r\n", preg_replace('/\x0D\x0A[\x09\x20]+/', ' ', $header));
        foreach( $fields as $field ) {
            if( preg_match('/([^:]+): (.+)/m', $field, $match) ) {
                $match[1] = preg_replace('/(?<=^|[\x09\x20\x2D])./e', 'strtoupper("\0")', strtolower(trim($match[1])));
                if( isset($retVal[$match[1]]) ) {
                    $retVal[$match[1]] = array($retVal[$match[1]], $match[2]);
                } else {
                    $retVal[$match[1]] = trim($match[2]);
                }
            }
        }
        return $retVal;
    }   
```

Just put it in the class somewhere.

Or you can install this package: [pecl_http](http://pecl.php.net/package/pecl_http)

**Comment by kmpsharma** [comment]
Thanks a lot Marteen.

--- On Wed, 6/1/11, MaartenC89 reply@reply.github.com wrote:

**Comment by Nganthoiba** [comment]
Wao! it really works out.

**Comment by loveyu** [comment]
@mcls 
Deprecated: preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead in PHP 7
You can update it.
